name: Run Unit and Integration Tests

on:
  workflow_call:

jobs:
  # First Job: Run Unit Tests
  unit-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Cache pip dependencies
      - name: Cache Poetry cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
            
      # Configure Git to use the Personal Access Token
      - name: Configure Git authentication
        run: |
          git config --global url."https://${{ secrets.LYRIC_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      # Install dependencies
      - name: Install dependencies
        run: |
          poetry install

      # Run unit tests with coverage
      - name: Run unit tests with coverage
        run: |
          poetry run pytest tests/units --cov-config=.coveragerc --cov -vv --color=yes 

  # Second Job: Run Integration Tests
  integration-tests:
    runs-on: ubuntu-latest
    name: Run Integration Tests
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Cache Poetry cache
      - name: Cache Poetry cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      # Configure Git to use the Personal Access Token
      - name: Configure Git authentication
        run: |
          git config --global url."https://${{ secrets.LYRIC_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      # Install dependencies
      - name: Install dependencies
        run: |
          poetry install

      # Run integration tests with coverage
      - name: Run integration tests with coverage
        run: |
          poetry run pytest tests/integration --cov-config=.coveragerc --cov -vv --color=yes 
