name: Run Unit test on PR

on:
    workflow_call:

jobs:
  test:
    name: Run pytest and check coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pylint
          pip install poetry
          poetry install --all-extras

      - name: Run pytest with coverage
        run: poetry run pytest --cov-config=.coveragerc --cov

      - name: Check coverage percentage
        run: |
          COVERAGE_THRESHOLD=80

          if [ -f ".coverage" ]; then
            coverage=$(poetry run coverage report | awk '/TOTAL/ { print substr($NF, 1, length($NF)-1) }')
          else
            coverage=0
          fi

          if (( $(echo "$coverage >= $COVERAGE_THRESHOLD" | bc -l) )); then
            echo "Code coverage is ${coverage}%."
            exit 0
          else
            echo "Code coverage is ${coverage}%. Minimum required coverage is ${COVERAGE_THRESHOLD}%."
            exit 1
          fi
